apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.GitlabEnvSlug | default .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.GitlabEnvSlug | default .Values.app }}
  maxUnavailable: 1

