{{- if .Values.validator.keys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.GitlabEnvSlug | default .Values.app }}
type: Opaque
data:
  secrets: {{ .Values.validator.keys | default "" }}
{{- end }}
